# ApexPlanet Data Analytics Internship - Task 1
## Data Immersion & Wrangling

Dataset: Sales Dataset

Objective:
To understand, assess, clean, transform, and prepare the sales dataset
for further analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file_path = "/content/ApexPlanet_DataAnalytics_Dataset.xlsx"

df = pd.read_excel(file_path, sheet_name="Sales_Dataset")

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [3]:
df.shape

(1000, 12)

In [4]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [6]:
df.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [7]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Order_ID"].duplicated().sum()

np.int64(8)

In [10]:
df[df["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77

In [11]:
df.dtypes

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [12]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [13]:
print("Gender:")
print(df["Gender"].value_counts(dropna=False))

print("\nCity:")
print(df["City"].value_counts(dropna=False))

print("\nProduct:")
print(df["Product"].value_counts(dropna=False))

print("\nCategory:")
print(df["Category"].value_counts(dropna=False))

Gender:
Gender
Male      511
Female    489
Name: count, dtype: int64

City:
City
Patna        135
Kolkata      133
Mumbai       131
Delhi        125
Hyderabad    125
Bengaluru    122
Gaya         117
Pune          99
NaN           13
Name: count, dtype: int64

Product:
Product
Mobile    184
Book      178
Laptop    170
Chair     159
Shoes     156
Rice      153
Name: count, dtype: int64

Category:
Category
Electronics    354
Education      178
Furniture      159
Fashion        156
Grocery        153
Name: count, dtype: int64

In [14]:
df[["Age", "Quantity", "Unit_Price", "Total_Sales"]].describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [15]:
df["Age"].value_counts(dropna=False).sort_index()

Age
18.0    16
19.0    15
20.0    23
21.0    29
22.0    26
23.0    18
24.0    20
25.0    11
26.0    17
27.0    23
28.0    22
29.0    13
30.0    35
31.0    19
32.0    27
33.0    23
34.0    20
35.0    20
36.0    17
37.0    28
38.0    22
39.0    21
40.0    19
41.0    20
42.0    12
43.0    22
44.0    24
45.0    18
46.0    16
47.0    22
48.0    18
49.0    18
50.0    19
51.0    18
52.0    25
53.0    18
54.0    23
55.0    25
56.0    20
57.0    21
58.0    21
59.0    14
60.0    17
61.0    19
62.0    25
63.0    17
64.0    23
65.0    21
NaN     20
Name: count, dtype: int64

In [16]:
df[(df["Age"] < 18) | (df["Age"] > 65)]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

In [17]:
df["Quantity"].value_counts().sort_index()

Quantity
1      96
2     103
3      96
4     112
5     112
6     112
7      81
8      91
9     100
10     97
Name: count, dtype: int64

In [18]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

In [19]:
df[df["Unit_Price"] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

In [20]:
df[df["Total_Sales"] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales]
Index: []

In [23]:
df["Calculated_Sales"] = df["Quantity"] * df["Unit_Price"]

df["Sales_Difference"] = (
    df["Total_Sales"] - df["Calculated_Sales"]
).abs()

df["Sales_Difference"].describe()

count    1.000000e+03
mean     4.248193e-12
std      1.167805e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.820766e-11
Name: Sales_Difference, dtype: float64

In [24]:
df[df["Sales_Difference"] > 0.01]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales, Calculated_Sales, Sales_Difference]
Index: []

In [25]:
cleaned_df = df.copy()

In [26]:
cleaned_df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Calculated_Sales,Sales_Difference
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,19808.39,0.0
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,139530.80,0.0
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,299928.48,0.0
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,256872.24,0.0
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,140365.90,0.0

In [27]:
cleaned_df["Order_Date"] = pd.to_datetime(
    cleaned_df["Order_Date"],
    errors="coerce"
)

In [28]:
cleaned_df["Order_Date"].dtype

dtype('<M8[ns]')

In [29]:
cleaned_df["Age"] = cleaned_df["Age"].fillna(
    cleaned_df["Age"].median()
)

In [30]:
cleaned_df["Age"].isnull().sum()

np.int64(0)

In [31]:
cleaned_df["City"] = cleaned_df["City"].fillna("Unknown")

In [32]:
text_columns = [
    "Order_ID",
    "Customer_ID",
    "Customer_Name",
    "Gender",
    "City",
    "Product",
    "Category"
]

for col in text_columns:
    cleaned_df[col] = cleaned_df[col].astype(str).str.strip()

In [33]:
cleaned_df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
Product             0
Category            0
Quantity            0
Unit_Price          0
Total_Sales         0
Calculated_Sales    0
Sales_Difference    0
dtype: int64

In [34]:
cleaned_df.duplicated().sum()

np.int64(0)

In [35]:
cleaned_df["Order_ID"].duplicated().sum()

np.int64(8)

In [36]:
print("Invalid Age:")
print(cleaned_df[(cleaned_df["Age"] < 18) | (cleaned_df["Age"] > 65)])

print("\nInvalid Quantity:")
print(cleaned_df[cleaned_df["Quantity"] <= 0])

print("\nInvalid Unit Price:")
print(cleaned_df[cleaned_df["Unit_Price"] <= 0])

print("\nInvalid Total Sales:")
print(cleaned_df[cleaned_df["Total_Sales"] <= 0])

Invalid Age:
Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales, Calculated_Sales, Sales_Difference]
Index: []

Invalid Quantity:
Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales, Calculated_Sales, Sales_Difference]
Index: []

Invalid Unit Price:
Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales, Calculated_Sales, Sales_Difference]
Index: []

Invalid Total Sales:
Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, Gender, City, Product, Category, Quantity, Unit_Price, Total_Sales, Calculated_Sales, Sales_Difference]
Index: []

In [37]:
cleaned_df["Calculated_Sales"] = (
    cleaned_df["Quantity"] * cleaned_df["Unit_Price"]
)

cleaned_df["Sales_Difference"] = (
    cleaned_df["Total_Sales"] - cleaned_df["Calculated_Sales"]
).abs()

In [38]:
cleaned_df["Sales_Difference"].describe()

count    1.000000e+03
mean     4.248193e-12
std      1.167805e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.820766e-11
Name: Sales_Difference, dtype: float64

In [39]:
print("Gender values:")
print(cleaned_df["Gender"].value_counts())

print("\nCity values:")
print(cleaned_df["City"].value_counts())

print("\nCategory values:")
print(cleaned_df["Category"].value_counts())

print("\nProduct values:")
print(cleaned_df["Product"].value_counts())

Gender values:
Gender
Male      511
Female    489
Name: count, dtype: int64

City values:
City
Patna        135
Kolkata      133
Mumbai       131
Delhi        125
Hyderabad    125
Bengaluru    122
Gaya         117
Pune          99
Unknown       13
Name: count, dtype: int64

Category values:
Category
Electronics    354
Education      178
Furniture      159
Fashion        156
Grocery        153
Name: count, dtype: int64

Product values:
Product
Mobile    184
Book      178
Laptop    170
Chair     159
Shoes     156
Rice      153
Name: count, dtype: int64

In [40]:
numeric_columns = [
    "Age",
    "Quantity",
    "Unit_Price",
    "Total_Sales"
]

for col in numeric_columns:
    Q1 = cleaned_df[col].quantile(0.25)
    Q3 = cleaned_df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = cleaned_df[
        (cleaned_df[col] < lower) |
        (cleaned_df[col] > upper)
    ]

    print(f"{col}: {len(outliers)} outliers")

Age: 0 outliers
Quantity: 0 outliers
Unit_Price: 0 outliers
Total_Sales: 19 outliers

In [41]:
cleaned_df = cleaned_df.drop(
    columns=["Calculated_Sales", "Sales_Difference"],
    errors="ignore"
)

In [42]:
print("Shape:", cleaned_df.shape)

print("\nMissing values:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows:")
print(cleaned_df.duplicated().sum())

print("\nData types:")
print(cleaned_df.dtypes)

Shape: (1000, 12)

Missing values:
Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

Duplicate rows:
0

Data types:
Order_ID                 object
Order_Date       datetime64[ns]
Customer_ID              object
Customer_Name            object
Age                     float64
Gender                   object
City                     object
Product                  object
Category                 object
Quantity                  int64
Unit_Price              float64
Total_Sales             float64
dtype: object

In [43]:
output_file = "/content/ApexPlanet_Task1_Cleaned_Dataset.xlsx"

cleaned_df.to_excel(
    output_file,
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!